# Generated by Django 4.2.5 on 2023-09-13 23:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios',
            name='data',
            field=models.DateField(default=datetime.datetime(2023, 9, 13, 23, 58, 49, 763467, tzinfo=datetime.timezone.utc)),
        ),
    ]
