# Generated by Django 4.2.5 on 2023-09-14 00:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_comentarios_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios',
            name='data',
            field=models.DateField(default=datetime.datetime(2023, 9, 14, 0, 8, 27, 175466, tzinfo=datetime.timezone.utc)),
        ),
    ]
