# Generated by Django 4.2.5 on 2023-09-14 01:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_comentarios_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamentos',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuario_cargo',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='comentarios',
            name='data',
            field=models.DateField(default=datetime.datetime(2023, 9, 14, 1, 31, 56, 297039, tzinfo=datetime.timezone.utc)),
        ),
    ]
